import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "cozy-shakshuka",
    title: "Cozy Shakshuka",
    description: "Jammy tomatoes, runny eggs, and a lot of bread for dunking.",
    emoji: "🍳",
    timeMinutes: 30,
    cost: "$10–14",
    servings: 2,
    diets: ["halal", "vegetarian", "gluten-free"],
    ingredients: [
      "olive oil",
      "onion",
      "garlic",
      "red bell pepper",
      "canned tomatoes",
      "cumin",
      "paprika",
      "eggs",
      "feta",
      "parsley",
    ],
    steps: [
      "Warm olive oil in a skillet and soften chopped onion and bell pepper.",
      "Add garlic, cumin, and paprika until the pan smells toasty.",
      "Pour in tomatoes and simmer until thick and jammy.",
      "Make little wells and crack in the eggs. Cover until the whites set.",
      "Scatter feta and parsley. Serve with something scoopable.",
    ],
    source: "kitchen",
  },
  {
    id: "gochujang-noodles",
    title: "Gochujang Butter Noodles",
    description: "Spicy-sweet weeknight noodles that taste like a hug.",
    emoji: "🍜",
    timeMinutes: 20,
    cost: "$8–12",
    servings: 2,
    diets: ["halal", "vegetarian"],
    ingredients: [
      "wheat noodles",
      "gochujang",
      "butter",
      "soy sauce",
      "honey",
      "garlic",
      "green onion",
      "sesame seeds",
    ],
    steps: [
      "Boil noodles until just tender, then save a splash of pasta water.",
      "Melt butter with garlic in a pan. Stir in gochujang, soy, and honey.",
      "Toss noodles with the sauce and a little pasta water until glossy.",
      "Finish with green onion and sesame seeds.",
    ],
    source: "kitchen",
  },
  {
    id: "lemon-chickpea-orzo",
    title: "Lemon Chickpea Orzo",
    description: "One-pot, bright, and very packed-lunch coded.",
    emoji: "🍋",
    timeMinutes: 25,
    cost: "$7–11",
    servings: 3,
    diets: ["halal", "vegetarian", "vegan"],
    ingredients: [
      "orzo",
      "chickpeas",
      "lemon",
      "spinach",
      "garlic",
      "olive oil",
      "vegetable broth",
      "dill",
    ],
    steps: [
      "Toast orzo in olive oil with garlic until it smells nutty.",
      "Add broth and chickpeas. Simmer until the orzo is tender.",
      "Fold in spinach, lemon juice, and dill.",
      "Taste for salt. Add more lemon if it needs a wink.",
    ],
    source: "kitchen",
  },
  {
    id: "strawberry-shortcake-cups",
    title: "Strawberry Shortcake Cups",
    description: "No-fuss dessert: jammy berries, cream, crumbly cake.",
    emoji: "🍓",
    timeMinutes: 15,
    cost: "$9–13",
    servings: 4,
    diets: ["halal", "vegetarian"],
    ingredients: [
      "strawberries",
      "sugar",
      "whipping cream",
      "vanilla",
      "pound cake",
    ],
    steps: [
      "Toss sliced strawberries with a spoon of sugar and let them get juicy.",
      "Whip cream with vanilla until soft peaks.",
      "Cube the pound cake and layer cake, berries, and cream in cups.",
      "Finish with extra berries on top. Eat immediately, obviously.",
    ],
    source: "kitchen",
  },
  {
    id: "crispy-tofu-rice",
    title: "Crispy Tofu Rice Bowl",
    description: "Crunchy edges, sticky rice, spicy-sweet drizzle.",
    emoji: "🍚",
    timeMinutes: 35,
    cost: "$11–15",
    servings: 2,
    diets: ["halal", "vegetarian", "vegan", "gluten-free"],
    ingredients: [
      "firm tofu",
      "rice",
      "cornstarch",
      "soy sauce",
      "maple syrup",
      "rice vinegar",
      "cucumber",
      "avocado",
      "chili flakes",
    ],
    steps: [
      "Press tofu, cube it, and toss with cornstarch.",
      "Pan-fry until every side is golden and loud.",
      "Whisk soy, maple, and vinegar. Glaze the tofu in the pan.",
      "Serve over rice with cucumber, avocado, and chili flakes.",
    ],
    source: "kitchen",
  },
  {
    id: "sheet-pan-harissa-chicken",
    title: "Sheet-Pan Harissa Chicken",
    description: "Spicy, sticky, and almost zero dishes.",
    emoji: "🌶️",
    timeMinutes: 40,
    cost: "$14–18",
    servings: 3,
    diets: ["halal", "gluten-free"],
    ingredients: [
      "chicken thighs",
      "harissa",
      "honey",
      "potato",
      "red onion",
      "olive oil",
      "lemon",
      "cilantro",
    ],
    steps: [
      "Heat the oven to 425°F. Toss potatoes and onion with oil and salt.",
      "Rub chicken with harissa and honey. Nestle onto the pan.",
      "Roast until the chicken is cooked through and the potatoes are crisp.",
      "Squeeze lemon over everything and shower with cilantro.",
    ],
    source: "kitchen",
  },
  {
    id: "brown-butter-banana-toast",
    title: "Brown Butter Banana Toast",
    description: "Breakfast that feels like dessert, on purpose.",
    emoji: "🍌",
    timeMinutes: 10,
    cost: "$4–6",
    servings: 1,
    diets: ["halal", "vegetarian"],
    ingredients: ["bread", "butter", "banana", "cinnamon", "salt", "honey"],
    steps: [
      "Brown the butter in a small pan until it smells like toffee.",
      "Toast the bread and spoon the brown butter over it.",
      "Add banana slices, cinnamon, a pinch of salt, and honey.",
    ],
    source: "kitchen",
  },
  {
    id: "miso-mushroom-udon",
    title: "Miso Mushroom Udon",
    description: "Slurpable, savory, rainy-day energy.",
    emoji: "🍄",
    timeMinutes: 28,
    cost: "$12–16",
    servings: 2,
    diets: ["halal", "vegetarian"],
    ingredients: [
      "udon noodles",
      "mixed mushrooms",
      "miso",
      "ginger",
      "garlic",
      "scallion",
      "butter",
      "soy sauce",
    ],
    steps: [
      "Sear mushrooms in butter until they shrink and brown.",
      "Add garlic and ginger. Splash in soy.",
      "Loosen miso with hot water and pour it over the mushrooms.",
      "Add cooked udon and toss. Top with scallions.",
    ],
    source: "kitchen",
  },
];

export function getRecipeById(
  id: string,
  extras: Recipe[] = [],
): Recipe | undefined {
  return [...extras, ...RECIPES].find((recipe) => recipe.id === id);
}
