import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "grilled-cheese",
    title: "Classic Grilled Cheese",
    description:
      "Crisp bread, melted cheddar, one pan. A 10-minute lunch that still feels like a treat.",
    emoji: "🧀",
    imageUrl:
      "https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 10,
    cost: "$3–5",
    servings: 1,
    diets: ["halal", "vegetarian"],
    meal: "lunch",
    ingredients: [
      "2 slices|sandwich bread",
      "2 tsp|butter",
      "2 slices|cheddar cheese",
    ],
    steps: [
      "Set a skillet over medium heat and let it warm for 1 minute.",
      "Spread 1 teaspoon butter on one side of each bread slice.",
      "Place one slice butter-side down in the pan. Add both cheddar slices, then the second bread slice butter-side up.",
      "Cook 2 to 3 minutes on medium until the bottom is golden. Flip and cook 2 minutes more until the cheese melts.",
      "Move to a plate, rest 30 seconds, then slice. That's a wrap — or a melt.",
    ],
    source: "kitchen",
  },
  {
    id: "skillet-quesadilla",
    title: "Skillet Quesadilla",
    description:
      "One tortilla, a handful of cheese, dinner in twelve minutes. Add beans if you have them.",
    emoji: "🌮",
    imageUrl:
      "https://images.unsplash.com/photo-1719957770167-bb66133ba808?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 12,
    cost: "$4–6",
    servings: 1,
    diets: ["halal", "vegetarian"],
    meal: "lunch",
    ingredients: [
      "1|flour tortilla",
      "1/2 cup|shredded cheese",
      "1/3 cup|canned black beans, rinsed",
      "1 tsp|oil",
    ],
    steps: [
      "Warm 1 teaspoon oil in a skillet over medium heat.",
      "Lay the tortilla in the pan. Sprinkle 1/2 cup cheese and 1/3 cup beans over one half.",
      "Fold the tortilla over. Press gently and cook 2 minutes on medium until toasted.",
      "Flip and cook 2 minutes more until the cheese is stretchy. Slice into wedges.",
    ],
    source: "kitchen",
  },
  {
    id: "soft-scrambled-toast",
    title: "Soft Scrambled Eggs on Toast",
    description:
      "Two eggs, one slice of toast, protein before class. Gentle heat keeps them creamy.",
    emoji: "🍳",
    imageUrl:
      "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 8,
    cost: "$3–5",
    servings: 1,
    diets: ["halal", "vegetarian"],
    meal: "breakfast",
    ingredients: [
      "2|eggs",
      "1 tsp|butter",
      "1 slice|bread",
      "1 pinch|salt",
    ],
    steps: [
      "Toast the slice of bread while you cook.",
      "Beat 2 eggs with a pinch of salt. Melt 1 teaspoon butter in a small pan over low heat.",
      "Pour in the eggs. Stir slowly over low heat until they just set, about 2 minutes. Do not rush to high.",
      "Pile the eggs on the toast. Breakfast, whisked and ready.",
    ],
    source: "kitchen",
  },
  {
    id: "peanut-banana-oats",
    title: "Peanut Butter Banana Oats",
    description:
      "Microwave oats, a banana, and a spoon of peanut butter. Filling, cheap, and ready before the kettle cools.",
    emoji: "🥣",
    imageUrl:
      "https://images.unsplash.com/photo-1645466525466-647ef246067f?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 5,
    cost: "$2–4",
    servings: 1,
    diets: ["halal", "vegetarian"],
    meal: "breakfast",
    ingredients: [
      "1/2 cup|rolled oats",
      "1 cup|water or milk",
      "1|banana",
      "1 tbsp|peanut butter",
      "1 pinch|cinnamon",
    ],
    steps: [
      "Stir 1/2 cup oats with 1 cup water or milk in a mug.",
      "Microwave on high for 90 seconds, then stir. Add 30 seconds if it looks thin.",
      "Slice the banana over the top. Swirl in 1 tablespoon peanut butter and a pinch of cinnamon.",
    ],
    source: "kitchen",
  },
  {
    id: "garlic-butter-pasta",
    title: "Garlic Butter Pasta",
    description:
      "Four ingredients, one pot of water, a skillet. Comfort food that still respects your grocery run.",
    emoji: "🍝",
    imageUrl:
      "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 15,
    cost: "$4–7",
    servings: 1,
    diets: ["halal", "vegetarian"],
    meal: "dinner",
    ingredients: [
      "4 oz|spaghetti",
      "2 tbsp|butter",
      "2 cloves|garlic, minced",
      "1 pinch|chili flakes",
      "1 tbsp|grated parmesan (optional)",
    ],
    steps: [
      "Boil the 4 ounces spaghetti in salted water until just tender. Save 1/4 cup pasta water, then drain.",
      "In a skillet over medium-low heat, melt 2 tablespoons butter. Add the 2 minced garlic cloves and a pinch of chili flakes. Cook 45 seconds — do not brown the garlic.",
      "Toss in the pasta and a splash of the saved water over medium heat until glossy.",
      "Finish with 1 tablespoon parmesan if you have it. Twirl and serve.",
    ],
    source: "kitchen",
  },
  {
    id: "chickpea-veggie-wrap",
    title: "Chickpea Veggie Wrap",
    description:
      "Mashed chickpeas, crunchy veg, no stove if you skip the toast. Packed-lunch energy.",
    emoji: "🌯",
    imageUrl:
      "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 12,
    cost: "$5–8",
    servings: 1,
    diets: ["halal", "vegetarian", "vegan"],
    meal: "lunch",
    ingredients: [
      "1/2 cup|canned chickpeas, rinsed",
      "1 tbsp|olive oil or tahini",
      "1|flour tortilla or wrap",
      "1/2 cup|lettuce or spinach",
      "1/4|cucumber, sliced",
      "1 pinch|salt and lemon",
    ],
    steps: [
      "Mash 1/2 cup chickpeas with 1 tablespoon oil or tahini, a pinch of salt, and a squeeze of lemon.",
      "Warm the tortilla in a dry pan over medium heat for 20 seconds a side, or leave it soft.",
      "Spread the chickpea mash down the center. Add 1/2 cup greens and the cucumber slices.",
      "Roll it tight. That's a handheld garden.",
    ],
    source: "kitchen",
  },
  {
    id: "weeknight-rice-beans",
    title: "Weeknight Rice and Beans",
    description:
      "Rice, a can of beans, cumin. A complete plate from the pantry, ready in about 20 minutes.",
    emoji: "🍚",
    imageUrl:
      "https://images.unsplash.com/photo-1543353071-873f17a7a088?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 20,
    cost: "$4–7",
    servings: 2,
    diets: ["halal", "vegetarian", "vegan", "gluten-free"],
    meal: "dinner",
    ingredients: [
      "1 cup|cooked rice (or 1/2 cup dry)",
      "1 can|black or pinto beans, rinsed",
      "1 tsp|oil",
      "1/2 tsp|cumin",
      "1/4|onion, diced",
      "1 pinch|salt",
    ],
    steps: [
      "If the rice is uncooked, simmer 1/2 cup dry rice in 1 cup water over low heat until fluffy, about 15 minutes.",
      "Warm 1 teaspoon oil in a skillet over medium heat. Soften the diced onion for 3 minutes.",
      "Add the rinsed beans, 1/2 teaspoon cumin, and a pinch of salt. Stir on medium for 4 minutes until steamy.",
      "Spoon the beans over the rice. A lime wedge is extra credit.",
    ],
    source: "kitchen",
  },
  {
    id: "sesame-ramen-upgrade",
    title: "Sesame Ramen Upgrade",
    description:
      "Instant noodles, plus an egg and greens. Same budget, much happier bowl.",
    emoji: "🍜",
    imageUrl:
      "https://images.unsplash.com/photo-1557872943-16a5ac26437e?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 12,
    cost: "$3–6",
    servings: 1,
    diets: ["halal", "vegetarian"],
    meal: "lunch",
    ingredients: [
      "1 pkg|instant ramen",
      "1|egg",
      "1 cup|spinach or frozen peas",
      "1 tsp|sesame oil or chili oil",
      "1|green onion (optional)",
    ],
    steps: [
      "Bring 2 cups water to a boil over high heat. Add the ramen noodles (save half the seasoning packet).",
      "After 1 minute on medium-high, crack in 1 egg and add 1 cup spinach or peas. Simmer 2 minutes.",
      "Stir in half the seasoning and 1 teaspoon sesame or chili oil. Off the heat.",
      "Top with sliced green onion if you have it. Slurp with pride.",
    ],
    source: "kitchen",
  },
  {
    id: "indomie-instant-noodles",
    title: "Indomie Instant Noodles",
    description:
      "A cup (or packet) of Indomie. Boil, mix the seasoning, eat. The classic dorm lunch.",
    emoji: "🍜",
    imageUrl:
      "https://images.unsplash.com/photo-1684707878393-02606f779d7f?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 5,
    cost: "$1–3",
    servings: 1,
    diets: ["halal"],
    meal: "lunch",
    ingredients: [
      "1 pack|Indomie instant noodles (Mi Goreng or cup)",
      "2 cups|water",
      "1|egg (optional)",
      "1|green onion, sliced (optional)",
    ],
    steps: [
      "Bring 2 cups water to a boil over high heat. If you have the cup, boil a kettle instead.",
      "Add the Indomie noodles. Cook 3 minutes on medium-high until just soft. For the cup, pour boiling water to the line and cover 3 minutes.",
      "Drain most of the water, leaving about 2 tablespoons so the seasoning clings. Cup noodles: do not drain.",
      "Stir in every packet — seasoning powder, chili, kecap, and the oil. Mix until the noodles look glossy.",
      "Crack in an egg while the noodles are still hot if you want it richer. Green onion on top. Lunch is served.",
    ],
    source: "kitchen",
  },
  {
    id: "yogurt-berry-bowl",
    title: "Yogurt Berry Crunch Bowl",
    description:
      "No stove. Yogurt, frozen berries, a handful of oats or cereal. Breakfast that does not argue with your morning.",
    emoji: "🫐",
    imageUrl:
      "https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 5,
    cost: "$3–6",
    servings: 1,
    diets: ["halal", "vegetarian", "gluten-free"],
    meal: "snack",
    ingredients: [
      "1 cup|plain yogurt",
      "1/2 cup|frozen or fresh berries",
      "2 tbsp|oats or granola",
      "1 tsp|honey",
    ],
    steps: [
      "Spoon 1 cup yogurt into a bowl.",
      "Add 1/2 cup berries. If frozen, wait 2 minutes so they thaw into the yogurt.",
      "Scatter 2 tablespoons oats or granola and drizzle 1 teaspoon honey.",
    ],
    source: "kitchen",
  },
  {
    id: "lemon-chickpea-orzo",
    title: "Lemon Chickpea Orzo",
    description:
      "One pot, bright lemon, a can of chickpeas. Easy leftovers that still taste like you tried.",
    emoji: "🍋",
    imageUrl:
      "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 25,
    cost: "$6–9",
    servings: 2,
    diets: ["halal", "vegetarian", "vegan"],
    meal: "lunch",
    ingredients: [
      "1 cup|orzo",
      "1 can|chickpeas, rinsed",
      "1|lemon",
      "2 cups|spinach",
      "2 cloves|garlic, minced",
      "1 tbsp|olive oil",
      "2 1/2 cups|vegetable broth or water",
    ],
    steps: [
      "Warm 1 tablespoon olive oil in a pot over medium heat. Add the 2 minced garlic cloves and 1 cup orzo. Toast 2 minutes until nutty.",
      "Pour in 2 1/2 cups broth and the chickpeas. Simmer on medium-low, stirring, until the orzo is tender, about 10 minutes.",
      "Fold in 2 cups spinach and the juice of the lemon over low heat until the greens wilt.",
      "Taste for salt. Another squeeze of lemon if it needs a wink.",
    ],
    source: "kitchen",
  },
  {
    id: "sheet-pan-veg-chicken",
    title: "Sheet-Pan Chicken and Potatoes",
    description:
      "One tray, oven does the work. Chicken, potatoes, and onion — cleanup is a single wash.",
    emoji: "🥔",
    imageUrl:
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 40,
    cost: "$9–13",
    servings: 2,
    diets: ["halal", "gluten-free"],
    meal: "dinner",
    ingredients: [
      "2|chicken thighs",
      "2|potatoes, cubed",
      "1/2|red onion, wedges",
      "1 tbsp|olive oil",
      "1 tsp|paprika",
      "1/2|lemon",
    ],
    steps: [
      "Heat the oven to 425°F. Toss 2 cubed potatoes and the onion with 1 tablespoon oil, 1 teaspoon paprika, and salt on a sheet pan.",
      "Nestle the 2 chicken thighs among the vegetables. Roast 25 to 30 minutes until the chicken is cooked through and the potatoes are crisp.",
      "Squeeze the lemon half over the tray. Dinner, with almost zero dishes.",
    ],
    source: "kitchen",
  },
  {
    id: "veggie-fried-rice",
    title: "Leftover Veggie Fried Rice",
    description:
      "Cold rice, frozen peas, one egg. The fridge-clearing classic that still tastes like takeout.",
    emoji: "🥘",
    imageUrl:
      "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 15,
    cost: "$4–7",
    servings: 1,
    diets: ["halal", "vegetarian"],
    meal: "dinner",
    ingredients: [
      "1 1/2 cups|cold cooked rice",
      "1|egg",
      "1/2 cup|frozen peas or mixed veg",
      "1 tbsp|soy sauce",
      "1 tsp|oil",
      "1 clove|garlic, minced",
    ],
    steps: [
      "Heat 1 teaspoon oil in a skillet over medium-high. Add the minced garlic for 20 seconds.",
      "Add 1/2 cup frozen veg. Stir 2 minutes until hot.",
      "Push veg aside. Scramble 1 egg on medium-high, then mix it in.",
      "Add 1 1/2 cups cold rice and 1 tablespoon soy sauce. Stir-fry 3 minutes until some grains toast. Serve hot.",
    ],
    source: "kitchen",
  },
  {
    id: "hummus-pita-snack",
    title: "Hummus & Pita Plate",
    description:
      "A five-minute snack plate: warm pita, hummus, and whatever crunchy veg is in the crisper.",
    emoji: "🧆",
    imageUrl:
      "https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 5,
    cost: "$3–5",
    servings: 1,
    diets: ["halal", "vegetarian", "vegan"],
    meal: "snack",
    ingredients: [
      "1|pita, warmed",
      "1/3 cup|hummus",
      "1/2|cucumber or carrot, sliced",
      "1 pinch|paprika or za'atar",
    ],
    steps: [
      "Warm the pita in a dry pan or microwave for 20 seconds.",
      "Spoon hummus onto a plate and swirl. Dust with paprika.",
      "Cut the pita into wedges and pile on cucumber or carrot. Dip and snack.",
    ],
    source: "kitchen",
  },
  {
    id: "microwave-mug-brownie",
    title: "Microwave Mug Brownie",
    description:
      "One mug, five minutes, chocolate emergency solved. Dessert without turning on the oven.",
    emoji: "🍫",
    imageUrl:
      "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 5,
    cost: "$2–4",
    servings: 1,
    diets: ["halal", "vegetarian"],
    meal: "dessert",
    ingredients: [
      "3 tbsp|flour",
      "3 tbsp|sugar",
      "2 tbsp|cocoa powder",
      "2 tbsp|oil or melted butter",
      "3 tbsp|milk",
      "1 pinch|salt",
    ],
    steps: [
      "Stir flour, sugar, cocoa, and a pinch of salt in a microwave-safe mug.",
      "Add the oil and milk. Mix until no dry pockets remain.",
      "Microwave on high for 60 to 75 seconds, until the top looks set and shiny.",
      "Wait 1 minute — it is lava-hot. Eat from the mug.",
    ],
    source: "kitchen",
  },
  {
    id: "banana-nice-cream",
    title: "Banana Nice Cream",
    description:
      "Frozen banana, a splash of milk, blend. Ice cream energy with one ingredient you already have.",
    emoji: "🍌",
    imageUrl:
      "https://images.unsplash.com/photo-1488900128323-21503983a07e?auto=format&fit=crop&w=1200&q=80",
    timeMinutes: 8,
    cost: "$2–4",
    servings: 1,
    diets: ["halal", "vegetarian", "vegan", "gluten-free"],
    meal: "dessert",
    ingredients: [
      "2|ripe bananas, sliced and frozen",
      "2 tbsp|milk or oat milk",
      "1 tsp|peanut butter or cocoa (optional)",
    ],
    steps: [
      "Freeze banana slices for at least 2 hours, or use ones you already froze.",
      "Blend the frozen banana with 2 tablespoons milk until it looks like soft-serve.",
      "Swirl in peanut butter or cocoa if you want. Eat right away before it melts.",
    ],
    source: "kitchen",
  },
];

export function getRecipeById(
  id: string,
  extras: Recipe[] = [],
): Recipe | undefined {
  return [...extras, ...RECIPES].find((recipe) => recipe.id === id);
}
